create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table public.approved_doctors (
  approved_doctor_id integer generated by default as identity primary key,
  full_name text not null,
  dni text not null,
  license_number text not null,
  organization text not null,
  specialty text,
  status text not null default 'approved',
  claimed_by_auth_user_id uuid unique null references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint approved_doctors_full_name_not_blank check (btrim(full_name) <> ''),
  constraint approved_doctors_dni_not_blank check (btrim(dni) <> ''),
  constraint approved_doctors_license_number_not_blank check (btrim(license_number) <> ''),
  constraint approved_doctors_organization_not_blank check (btrim(organization) <> ''),
  constraint approved_doctors_specialty_not_blank check (specialty is null or btrim(specialty) <> ''),
  constraint approved_doctors_status_check check (status in ('pending', 'approved', 'rejected', 'suspended'))
);

create table public.active_doctors (
  active_doctor_id integer generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  approved_doctor_id integer not null unique references public.approved_doctors (approved_doctor_id) on delete restrict,
  name text not null,
  dni text not null,
  email text not null,
  phone text not null,
  type text not null default 'obra_social',
  organization text not null,
  license_number text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint active_doctors_name_not_blank check (btrim(name) <> ''),
  constraint active_doctors_dni_not_blank check (btrim(dni) <> ''),
  constraint active_doctors_email_not_blank check (btrim(email) <> ''),
  constraint active_doctors_email_format_check check (position('@' in email) > 1),
  constraint active_doctors_phone_not_blank check (btrim(phone) <> ''),
  constraint active_doctors_type_not_blank check (btrim(type) <> ''),
  constraint active_doctors_organization_not_blank check (btrim(organization) <> ''),
  constraint active_doctors_license_number_not_blank check (btrim(license_number) <> '')
);

create table public.pharmacies (
  pharmacy_id integer generated by default as identity primary key,
  name text not null,
  location text,
  address text,
  zone text,
  city text,
  whatsapp_number text,
  accepts_digital_prescription boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint pharmacies_name_not_blank check (btrim(name) <> ''),
  constraint pharmacies_location_not_blank check (location is null or btrim(location) <> ''),
  constraint pharmacies_address_not_blank check (address is null or btrim(address) <> ''),
  constraint pharmacies_zone_not_blank check (zone is null or btrim(zone) <> ''),
  constraint pharmacies_city_not_blank check (city is null or btrim(city) <> ''),
  constraint pharmacies_whatsapp_number_not_blank check (whatsapp_number is null or btrim(whatsapp_number) <> '')
);

create table public.patients (
  patient_id integer generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  name text not null,
  dni text not null,
  email text not null,
  phone text,
  address text,
  zone text,
  preferred_pharmacy_id integer null references public.pharmacies (pharmacy_id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint patients_name_not_blank check (btrim(name) <> ''),
  constraint patients_dni_not_blank check (btrim(dni) <> ''),
  constraint patients_email_not_blank check (btrim(email) <> ''),
  constraint patients_email_format_check check (position('@' in email) > 1),
  constraint patients_phone_not_blank check (phone is null or btrim(phone) <> ''),
  constraint patients_address_not_blank check (address is null or btrim(address) <> ''),
  constraint patients_zone_not_blank check (zone is null or btrim(zone) <> '')
);

create table public.patient_doctors (
  patient_doctor_id integer generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer not null references public.active_doctors (active_doctor_id) on delete cascade,
  role text,
  is_primary boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint patient_doctors_role_not_blank check (role is null or btrim(role) <> ''),
  constraint patient_doctors_unique_relationship unique (patient_id, active_doctor_id)
);

create unique index approved_doctors_dni_key on public.approved_doctors (dni);
create unique index approved_doctors_license_number_key on public.approved_doctors (license_number);
create index approved_doctors_status_idx on public.approved_doctors (status);
create index approved_doctors_claimed_by_auth_user_id_idx on public.approved_doctors (claimed_by_auth_user_id);

create unique index active_doctors_dni_key on public.active_doctors (dni);
create unique index active_doctors_email_key on public.active_doctors (email);
create index active_doctors_auth_user_id_idx on public.active_doctors (auth_user_id);
create index active_doctors_approved_doctor_id_idx on public.active_doctors (approved_doctor_id);

create unique index patients_dni_key on public.patients (dni);
create unique index patients_email_key on public.patients (email);
create index patients_auth_user_id_idx on public.patients (auth_user_id);
create index patients_preferred_pharmacy_id_idx on public.patients (preferred_pharmacy_id);

create index patient_doctors_patient_id_idx on public.patient_doctors (patient_id);
create index patient_doctors_active_doctor_id_idx on public.patient_doctors (active_doctor_id);
create unique index patient_doctors_primary_unique_idx
  on public.patient_doctors (patient_id)
  where is_primary;

create index pharmacies_name_idx on public.pharmacies (name);
create index pharmacies_zone_idx on public.pharmacies (zone);
create index pharmacies_city_idx on public.pharmacies (city);

create trigger set_approved_doctors_updated_at
before update on public.approved_doctors
for each row
execute function public.set_updated_at();

create trigger set_active_doctors_updated_at
before update on public.active_doctors
for each row
execute function public.set_updated_at();

create trigger set_patients_updated_at
before update on public.patients
for each row
execute function public.set_updated_at();

create trigger set_patient_doctors_updated_at
before update on public.patient_doctors
for each row
execute function public.set_updated_at();

create trigger set_pharmacies_updated_at
before update on public.pharmacies
for each row
execute function public.set_updated_at();
