create or replace function public.is_valid_weekday_array(p_days smallint[])
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    p_days is not null
    and coalesce(array_length(p_days, 1), 0) > 0
    and not exists (
      select 1
      from unnest(p_days) as schedule_day
      where schedule_day < 0 or schedule_day > 6
    );
$$;

create or replace function public.is_valid_intake_slots_jsonb(p_slots jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    jsonb_typeof(p_slots) = 'array'
    and p_slots <> '[]'::jsonb
    and not exists (
      select 1
      from jsonb_array_elements(p_slots) as slot
      where jsonb_typeof(slot) <> 'object'
        or coalesce(nullif(btrim(slot ->> 'slot_key'), ''), '') = ''
        or (
          slot ? 'label'
          and jsonb_typeof(slot -> 'label') <> 'string'
        )
        or (
          slot ? 'time'
          and not (
            jsonb_typeof(slot -> 'time') = 'string'
            and (slot ->> 'time') ~ '^\d{2}:\d{2}$'
          )
        )
    );
$$;

create table public.weekly_schedule_configs (
  weekly_schedule_config_id integer generated by default as identity primary key,
  patient_medication_id integer not null
    references public.patient_medications (patient_medication_id)
    on delete cascade,
  patient_id integer not null
    references public.patients (patient_id)
    on delete cascade,
  active_doctor_id integer not null
    references public.active_doctors (active_doctor_id)
    on delete restrict,
  is_enabled boolean not null default true,
  schedule_start_date date not null,
  schedule_end_date date null,
  days_of_week smallint[] not null,
  intake_slots jsonb not null,
  notes text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint weekly_schedule_configs_patient_medication_unique
    unique (patient_medication_id),
  constraint weekly_schedule_configs_notes_not_blank
    check (notes is null or btrim(notes) <> ''),
  constraint weekly_schedule_configs_schedule_end_after_start
    check (schedule_end_date is null or schedule_end_date >= schedule_start_date),
  constraint weekly_schedule_configs_days_valid
    check (public.is_valid_weekday_array(days_of_week)),
  constraint weekly_schedule_configs_slots_valid
    check (public.is_valid_intake_slots_jsonb(intake_slots))
);

create index weekly_schedule_configs_patient_id_enabled_idx
  on public.weekly_schedule_configs (patient_id, is_enabled);

create index weekly_schedule_configs_active_doctor_id_enabled_idx
  on public.weekly_schedule_configs (active_doctor_id, is_enabled);

create index weekly_schedule_configs_start_date_idx
  on public.weekly_schedule_configs (schedule_start_date desc);

create trigger set_weekly_schedule_configs_updated_at
before update on public.weekly_schedule_configs
for each row
execute function public.set_updated_at();

create table public.weekly_schedule_logs (
  weekly_schedule_log_id integer generated by default as identity primary key,
  weekly_schedule_config_id integer not null
    references public.weekly_schedule_configs (weekly_schedule_config_id)
    on delete cascade,
  patient_medication_id integer not null
    references public.patient_medications (patient_medication_id)
    on delete cascade,
  patient_id integer not null
    references public.patients (patient_id)
    on delete cascade,
  active_doctor_id integer not null
    references public.active_doctors (active_doctor_id)
    on delete restrict,
  scheduled_for_date date not null,
  slot_key text not null,
  scheduled_time time null,
  status text not null,
  recorded_by_role text not null default 'patient',
  recorded_by_auth_user_id uuid null
    references auth.users (id)
    on delete set null,
  note text null,
  logged_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint weekly_schedule_logs_unique_dose
    unique (weekly_schedule_config_id, scheduled_for_date, slot_key),
  constraint weekly_schedule_logs_slot_key_not_blank
    check (btrim(slot_key) <> ''),
  constraint weekly_schedule_logs_status_check
    check (status in ('taken', 'missed', 'taken_late')),
  constraint weekly_schedule_logs_recorded_by_role_check
    check (recorded_by_role in ('patient', 'doctor', 'system')),
  constraint weekly_schedule_logs_note_not_blank
    check (note is null or btrim(note) <> '')
);

create index weekly_schedule_logs_config_date_idx
  on public.weekly_schedule_logs (weekly_schedule_config_id, scheduled_for_date desc);

create index weekly_schedule_logs_patient_date_idx
  on public.weekly_schedule_logs (patient_id, scheduled_for_date desc);

create index weekly_schedule_logs_medication_date_idx
  on public.weekly_schedule_logs (patient_medication_id, scheduled_for_date desc);

create index weekly_schedule_logs_doctor_date_idx
  on public.weekly_schedule_logs (active_doctor_id, scheduled_for_date desc);

create index weekly_schedule_logs_status_date_idx
  on public.weekly_schedule_logs (status, scheduled_for_date desc);

create trigger set_weekly_schedule_logs_updated_at
before update on public.weekly_schedule_logs
for each row
execute function public.set_updated_at();

create or replace function public.enforce_weekly_schedule_config_consistency()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_medication public.patient_medications%rowtype;
begin
  select *
  into v_medication
  from public.patient_medications
  where patient_medication_id = new.patient_medication_id;

  if not found then
    raise exception 'Patient medication not found'
      using errcode = 'P0001', detail = 'patient_medication_not_found';
  end if;

  if new.patient_id <> v_medication.patient_id then
    raise exception 'Weekly schedule patient mismatch'
      using errcode = 'P0001', detail = 'weekly_schedule_patient_mismatch';
  end if;

  if new.active_doctor_id <> v_medication.active_doctor_id then
    raise exception 'Weekly schedule doctor mismatch'
      using errcode = 'P0001', detail = 'weekly_schedule_doctor_mismatch';
  end if;

  return new;
end;
$$;

create trigger enforce_weekly_schedule_config_consistency_trigger
before insert or update on public.weekly_schedule_configs
for each row
execute function public.enforce_weekly_schedule_config_consistency();

create or replace function public.enforce_weekly_schedule_log_consistency()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_config public.weekly_schedule_configs%rowtype;
begin
  select *
  into v_config
  from public.weekly_schedule_configs
  where weekly_schedule_config_id = new.weekly_schedule_config_id;

  if not found then
    raise exception 'Weekly schedule config not found'
      using errcode = 'P0001', detail = 'weekly_schedule_config_not_found';
  end if;

  if new.patient_medication_id <> v_config.patient_medication_id then
    raise exception 'Weekly schedule log medication mismatch'
      using errcode = 'P0001', detail = 'weekly_schedule_log_medication_mismatch';
  end if;

  if new.patient_id <> v_config.patient_id then
    raise exception 'Weekly schedule log patient mismatch'
      using errcode = 'P0001', detail = 'weekly_schedule_log_patient_mismatch';
  end if;

  if new.active_doctor_id <> v_config.active_doctor_id then
    raise exception 'Weekly schedule log doctor mismatch'
      using errcode = 'P0001', detail = 'weekly_schedule_log_doctor_mismatch';
  end if;

  return new;
end;
$$;

create trigger enforce_weekly_schedule_log_consistency_trigger
before insert or update on public.weekly_schedule_logs
for each row
execute function public.enforce_weekly_schedule_log_consistency();

alter table public.weekly_schedule_configs enable row level security;
alter table public.weekly_schedule_logs enable row level security;
