create table public.patient_chat_logs (
  patient_chat_log_id bigint generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer null references public.active_doctors (active_doctor_id) on delete set null,
  patient_medication_id integer null references public.patient_medications (patient_medication_id) on delete set null,
  message_user text not null,
  message_ai text not null,
  severity text not null,
  risk_score numeric(5,4) not null,
  symptom_tags jsonb not null default '[]'::jsonb,
  context_snapshot jsonb not null default '{}'::jsonb,
  llm_provider text not null default 'gemini',
  llm_model text null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint patient_chat_logs_severity_check
    check (severity in ('normal', 'warning', 'critical')),
  constraint patient_chat_logs_message_user_not_blank
    check (btrim(message_user) <> ''),
  constraint patient_chat_logs_message_ai_not_blank
    check (btrim(message_ai) <> ''),
  constraint patient_chat_logs_risk_score_check
    check (risk_score >= 0 and risk_score <= 1),
  constraint patient_chat_logs_symptom_tags_is_array
    check (jsonb_typeof(symptom_tags) = 'array'),
  constraint patient_chat_logs_context_snapshot_is_object
    check (jsonb_typeof(context_snapshot) = 'object')
);

create index patient_chat_logs_patient_created_idx
  on public.patient_chat_logs (patient_id, created_at desc);

create index patient_chat_logs_doctor_created_idx
  on public.patient_chat_logs (active_doctor_id, created_at desc)
  where active_doctor_id is not null;

create index patient_chat_logs_severity_created_idx
  on public.patient_chat_logs (severity, created_at desc);

alter table public.patient_chat_logs enable row level security;

create table public.doctor_patient_alerts (
  doctor_patient_alert_id bigint generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer not null references public.active_doctors (active_doctor_id) on delete cascade,
  patient_chat_log_id bigint null references public.patient_chat_logs (patient_chat_log_id) on delete set null,
  severity text not null,
  title text not null,
  message text not null,
  status text not null default 'open',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  acknowledged_at timestamptz null,
  closed_at timestamptz null,
  constraint doctor_patient_alerts_severity_check
    check (severity in ('warning', 'critical')),
  constraint doctor_patient_alerts_status_check
    check (status in ('open', 'acknowledged', 'closed')),
  constraint doctor_patient_alerts_title_not_blank
    check (btrim(title) <> ''),
  constraint doctor_patient_alerts_message_not_blank
    check (btrim(message) <> ''),
  constraint doctor_patient_alerts_metadata_is_object
    check (jsonb_typeof(metadata) = 'object'),
  constraint doctor_patient_alerts_acknowledged_at_consistency
    check (
      (status = 'open' and acknowledged_at is null and closed_at is null)
      or (status = 'acknowledged' and acknowledged_at is not null and closed_at is null)
      or (status = 'closed' and closed_at is not null)
    )
);

create index doctor_patient_alerts_doctor_status_created_idx
  on public.doctor_patient_alerts (active_doctor_id, status, created_at desc);

create index doctor_patient_alerts_patient_created_idx
  on public.doctor_patient_alerts (patient_id, created_at desc);

create trigger set_doctor_patient_alerts_updated_at
before update on public.doctor_patient_alerts
for each row
execute function public.set_updated_at();

alter table public.doctor_patient_alerts enable row level security;

create table public.patient_weekly_risk_snapshots (
  patient_weekly_risk_snapshot_id bigint generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer not null references public.active_doctors (active_doctor_id) on delete cascade,
  week_start date not null,
  week_end date not null,
  adherence_score numeric(5,4) not null,
  symptom_score numeric(5,4) not null,
  request_score numeric(5,4) not null,
  final_risk_score numeric(5,4) not null,
  final_status text not null,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint patient_weekly_risk_snapshots_score_bounds_check
    check (
      adherence_score >= 0 and adherence_score <= 1
      and symptom_score >= 0 and symptom_score <= 1
      and request_score >= 0 and request_score <= 1
      and final_risk_score >= 0 and final_risk_score <= 1
    ),
  constraint patient_weekly_risk_snapshots_final_status_check
    check (final_status in ('normal', 'warning', 'critical')),
  constraint patient_weekly_risk_snapshots_summary_is_object
    check (jsonb_typeof(summary) = 'object'),
  constraint patient_weekly_risk_snapshots_week_range_check
    check (week_start <= week_end),
  unique (patient_id, week_start)
);

create index patient_weekly_risk_snapshots_doctor_week_idx
  on public.patient_weekly_risk_snapshots (active_doctor_id, week_start desc);

create index patient_weekly_risk_snapshots_patient_week_idx
  on public.patient_weekly_risk_snapshots (patient_id, week_start desc);

alter table public.patient_weekly_risk_snapshots enable row level security;
