create table public.patient_notifications (
  patient_notification_id bigint generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer null references public.active_doctors (active_doctor_id) on delete set null,
  patient_medication_id integer null references public.patient_medications (patient_medication_id) on delete set null,
  prescription_request_id integer null references public.prescription_requests (prescription_request_id) on delete set null,
  weekly_schedule_config_id integer null references public.weekly_schedule_configs (weekly_schedule_config_id) on delete set null,
  source text not null default 'system',
  category text not null,
  type text not null,
  title text not null,
  message text not null,
  status text not null default 'unread',
  priority text not null default 'normal',
  action_url text null,
  metadata jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz null,
  read_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  dedupe_key text null,
  constraint patient_notifications_source_check
    check (source in ('system', 'doctor', 'pharmacy', 'calendar')),
  constraint patient_notifications_category_check
    check (category in ('calendar', 'prescription', 'doctor_message', 'system')),
  constraint patient_notifications_status_check
    check (status in ('unread', 'read')),
  constraint patient_notifications_priority_check
    check (priority in ('low', 'normal', 'high')),
  constraint patient_notifications_type_not_blank
    check (btrim(type) <> ''),
  constraint patient_notifications_title_not_blank
    check (btrim(title) <> ''),
  constraint patient_notifications_message_not_blank
    check (btrim(message) <> ''),
  constraint patient_notifications_action_url_not_blank
    check (action_url is null or btrim(action_url) <> ''),
  constraint patient_notifications_metadata_is_object
    check (jsonb_typeof(metadata) = 'object'),
  constraint patient_notifications_read_at_consistency
    check (
      (status = 'unread' and read_at is null)
      or (status = 'read' and read_at is not null)
    )
);

create index patient_notifications_patient_created_idx
  on public.patient_notifications (patient_id, created_at desc);

create index patient_notifications_patient_status_created_idx
  on public.patient_notifications (patient_id, status, created_at desc);

create index patient_notifications_patient_category_created_idx
  on public.patient_notifications (patient_id, category, created_at desc);

create index patient_notifications_prescription_request_idx
  on public.patient_notifications (prescription_request_id)
  where prescription_request_id is not null;

create index patient_notifications_medication_idx
  on public.patient_notifications (patient_medication_id)
  where patient_medication_id is not null;

create index patient_notifications_weekly_schedule_idx
  on public.patient_notifications (weekly_schedule_config_id)
  where weekly_schedule_config_id is not null;

create unique index patient_notifications_patient_dedupe_key_idx
  on public.patient_notifications (patient_id, dedupe_key)
  where dedupe_key is not null;

create trigger set_patient_notifications_updated_at
before update on public.patient_notifications
for each row
execute function public.set_updated_at();

alter table public.patient_notifications enable row level security;
