alter table public.patients
add column created_by_active_doctor_id integer references public.active_doctors (active_doctor_id) on delete restrict,
add column account_status text not null default 'invited',
add column invited_at timestamptz not null default timezone('utc', now()),
add column activated_at timestamptz null;

update public.patients
set created_by_active_doctor_id = (
  select pd.active_doctor_id
  from public.patient_doctors as pd
  where pd.patient_id = public.patients.patient_id
  order by pd.is_primary desc, pd.created_at asc
  limit 1
)
where exists (
  select 1
  from public.patient_doctors as pd
  where pd.patient_id = public.patients.patient_id
)
  and public.patients.created_by_active_doctor_id is null;

alter table public.patients
alter column created_by_active_doctor_id set not null;

alter table public.patients
add constraint patients_account_status_check
check (account_status in ('invited', 'active', 'disabled'));

create index patients_created_by_active_doctor_id_idx
  on public.patients (created_by_active_doctor_id);

create index patients_account_status_idx
  on public.patients (account_status);

create table public.patient_medications (
  patient_medication_id integer generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer not null references public.active_doctors (active_doctor_id) on delete restrict,
  medication_name text not null,
  presentation text null,
  dose_text text not null,
  frequency_text text not null,
  pills_per_box integer null,
  units_per_intake numeric(10,2) null,
  intakes_per_day numeric(10,2) null,
  notes text null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint patient_medications_medication_name_not_blank check (btrim(medication_name) <> ''),
  constraint patient_medications_presentation_not_blank check (presentation is null or btrim(presentation) <> ''),
  constraint patient_medications_dose_text_not_blank check (btrim(dose_text) <> ''),
  constraint patient_medications_frequency_text_not_blank check (btrim(frequency_text) <> ''),
  constraint patient_medications_notes_not_blank check (notes is null or btrim(notes) <> ''),
  constraint patient_medications_pills_per_box_check check (pills_per_box is null or pills_per_box > 0),
  constraint patient_medications_units_per_intake_check check (units_per_intake is null or units_per_intake > 0),
  constraint patient_medications_intakes_per_day_check check (intakes_per_day is null or intakes_per_day > 0)
);

create index patient_medications_patient_id_idx
  on public.patient_medications (patient_id);

create index patient_medications_active_doctor_id_idx
  on public.patient_medications (active_doctor_id);

create index patient_medications_patient_active_idx
  on public.patient_medications (patient_id)
  where is_active;

create trigger set_patient_medications_updated_at
before update on public.patient_medications
for each row
execute function public.set_updated_at();

create table public.prescription_requests (
  prescription_request_id integer generated by default as identity primary key,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer not null references public.active_doctors (active_doctor_id) on delete restrict,
  patient_medication_id integer not null references public.patient_medications (patient_medication_id) on delete restrict,
  preferred_pharmacy_id integer null references public.pharmacies (pharmacy_id) on delete set null,
  status text not null default 'pending',
  requested_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz null,
  patient_note text null,
  doctor_note text null,
  medication_name_snapshot text not null,
  dose_snapshot text not null,
  frequency_snapshot text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint prescription_requests_status_check check (status in ('pending', 'reviewed', 'uploaded', 'rejected', 'cancelled')),
  constraint prescription_requests_patient_note_not_blank check (patient_note is null or btrim(patient_note) <> ''),
  constraint prescription_requests_doctor_note_not_blank check (doctor_note is null or btrim(doctor_note) <> ''),
  constraint prescription_requests_medication_name_snapshot_not_blank check (btrim(medication_name_snapshot) <> ''),
  constraint prescription_requests_dose_snapshot_not_blank check (btrim(dose_snapshot) <> ''),
  constraint prescription_requests_frequency_snapshot_not_blank check (btrim(frequency_snapshot) <> '')
);

create index prescription_requests_active_doctor_status_requested_idx
  on public.prescription_requests (active_doctor_id, status, requested_at desc);

create index prescription_requests_patient_requested_idx
  on public.prescription_requests (patient_id, requested_at desc);

create index prescription_requests_patient_medication_id_idx
  on public.prescription_requests (patient_medication_id);

create trigger set_prescription_requests_updated_at
before update on public.prescription_requests
for each row
execute function public.set_updated_at();

create table public.prescription_files (
  prescription_file_id integer generated by default as identity primary key,
  prescription_request_id integer not null references public.prescription_requests (prescription_request_id) on delete cascade,
  patient_id integer not null references public.patients (patient_id) on delete cascade,
  active_doctor_id integer not null references public.active_doctors (active_doctor_id) on delete restrict,
  storage_bucket text not null default 'prescriptions',
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  file_size_bytes bigint null,
  uploaded_at timestamptz not null default timezone('utc', now()),
  is_current boolean not null default true,
  constraint prescription_files_storage_bucket_not_blank check (btrim(storage_bucket) <> ''),
  constraint prescription_files_storage_path_not_blank check (btrim(storage_path) <> ''),
  constraint prescription_files_original_filename_not_blank check (btrim(original_filename) <> ''),
  constraint prescription_files_mime_type_not_blank check (btrim(mime_type) <> ''),
  constraint prescription_files_file_size_bytes_check check (file_size_bytes is null or file_size_bytes > 0)
);

create index prescription_files_prescription_request_id_idx
  on public.prescription_files (prescription_request_id);

create index prescription_files_patient_id_idx
  on public.prescription_files (patient_id);

create index prescription_files_active_doctor_id_idx
  on public.prescription_files (active_doctor_id);

create unique index prescription_files_current_per_request_idx
  on public.prescription_files (prescription_request_id)
  where is_current;

insert into storage.buckets (id, name, public)
values ('prescriptions', 'prescriptions', false)
on conflict (id) do update
set public = excluded.public;

alter table public.patient_medications enable row level security;
alter table public.prescription_requests enable row level security;
alter table public.prescription_files enable row level security;
